### ISSUE TITLE
Crash issue in 4.2,4.3,4.4

### ISSUE THREAD

**Issue by KishanViramgama** [FolioReader/FolioReader-Android#205] opened 2018-05-12 09:34 UTC
Issue with android 4.2,4.3,4.4

When open epub file and then minimized and open again and pressed back then instead of going into previous activity it closes app, and then opened again then app is crashed

when epub file is open in app and then app is closed by swiping and then reopen app then app crashes

This issue is in latest update of library
App working fine in latest android (8.0)

i need help please help me

**Comment by hrishikesh-kadam** [comment] 2018-05-14 14:09
> When open epub file and then minimized and open again and pressed back then instead of going into previous activity it closes app, and then opened again then app is crashed

This bug is reproducible and will get fixed in next release. But I am unable to reproduce following issue.

> when epub file is open in app and then app is closed by swiping and then reopen app then app crashes

Can you please give me epub file on which above bug is reproducible?

**Comment by KishanViramgama** [comment] 2018-05-15 03:47
Thanks for ans please check the problem

**Closed** 2018-05-16 13:58 UTC
