### ISSUE TITLE
The reader crashes on changing the orientation

### ISSUE THREAD

**Issue by kiyos88** [FolioReader/FolioReader-Android#33] opened 2016-10-26 11:19 UTC
here is the logcat

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.a360ground.reader10/com.folioreader.activity.FolioActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2712)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2777)
                                                                             at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4492)
                                                                             at android.app.ActivityThread.access$1000(ActivityThread.java:179)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1468)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:145)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5972)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
                                                                          Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
                                                                             at com.folioreader.activity.FolioActivity.readHTmlString(FolioActivity.java:458)
                                                                             at com.folioreader.activity.FolioActivity.getChapterHtmlContent(FolioActivity.java:438)
                                                                             at com.folioreader.fragments.FolioPageFragment.initWebView(FolioPageFragment.java:172)
                                                                             at com.folioreader.fragments.FolioPageFragment.onCreateView(FolioPageFragment.java:151)
                                                                             at android.support.v4.app.Fragment.performCreateView(Fragment.java:2074)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1268)
                                                                             at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2143)
                                                                             at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
                                                                             at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:615)
                                                                             at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1234)
                                                                             at android.app.Activity.performStart(Activity.java:6329)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2675)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2777) 
                                                                             at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4492) 
                                                                             at android.app.ActivityThread.access$1000(ActivityThread.java:179) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1468) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:145) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5972) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)`

**Comment by mahavir-jain** [comment] 2016-10-26 14:32
@kiyos88 we cannot able to reproduce here.. which device did you tried? can you share project in which you reproduced this bug?

**Comment by kiyos88** [comment] 2016-10-27 05:54
i tried in almost 5 devices it gives me the same error the project is exactly your project in github

**Comment by mahavir-jain** [comment] 2016-12-07 15:50
it has been fixed with v0.2.3..

**Closed by mahavir-jain** 2016-12-07 15:50 UTC
