### ISSUE TITLE
java.lang.IndexOutOfBoundsException:  at FolioActivity.java:149

### ISSUE THREAD

**Issue by SonyGeorge** [FolioReader/FolioReader-Android#245] opened 2018-07-24 14:32 UTC
java.lang.IndexOutOfBoundsException: 
   at java.util.ArrayList.get (ArrayList.java:437)
   at com.folioreader.ui.folio.activity.FolioActivity.startContentHighlightActivity (FolioActivity.java:149)
   at com.folioreader.view.FolioToolbar$initListeners$1.onClick (FolioToolbar.kt:50)
   at android.view.View.performClick (View.java:6897)
   at android.view.View$PerformClick.run (View.java:26101)
   at android.os.Handler.handleCallback (Handler.java:789)
   at android.os.Handler.dispatchMessage (Handler.java:98)
   at android.os.Looper.loop (Looper.java:164)
   at android.app.ActivityThread.main (ActivityThread.java:6944)
   at java.lang.reflect.Method.invoke (Native Method)
   at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)

**Comment by hrishikesh-kadam** [comment] 2018-07-25 06:31
This has been fixed in commit https://github.com/codetoart/FolioReader-Android/commit/d1d28fc2d917094c1361266b671d32c4d9a8b6ac
This code will get released in proposed v0.4.1 which will also have search feature.

Duplicate of #184

**Comment by hrishikesh-kadam** [comment] 2018-08-20 14:43
Fixed in v0.4.1

**Closed** 2018-08-20 14:57 UTC
