### ISSUE TITLE
New Copy Share popup menu appear in UI other than the default folio menu

### ISSUE THREAD

**Issue by SonyGeorge** [FolioReader/FolioReader-Android#231] opened 2018-06-30 14:08 UTC
Hi Team,
Thank you for making this great library....

in the new release (0.4.0) if we select a text, then the action menu will appear,
if we click anywhere outside of selection, then another action menu again appear.
please have a look at the images
I have tested this on my emulator

1) [image 1](https://ibb.co/gtTigd) select text, folio action menu appear,
2) [image 2](https://ibb.co/faSgZy), click outside the selected text, folio action menu disappear and another action menu appear with different style
3) [image 3](https://ibb.co/bXtG1d), expansion of second action menu

Thanks and Regards
Sony George

**Comment by hrishikesh-kadam** [comment] 2018-08-21 14:06
@SonyGeorge Unable to reproduce in FolioReader stock v0.4.0 or v0.4.1

**Comment by mahavir155** [comment] 2018-11-27 12:15
No reply.. Closing the issue.. If still reproducible, you can reopen it..

**Closed by mahavir155** 2018-11-27 12:15 UTC
