### ISSUE TITLE
Crash on SearchActivity

### ISSUE THREAD

**Issue by losscommand** [FolioReader/FolioReader-Android#274] opened 2018-09-03 14:21 UTC
Issue / Feature - Issue
FolioReader version -  0.4.2
FolioReader Stock / Modified -  Stock
Android SDK - 7.0
Mobile / Tablet / Emulator Info -  Samsung Galaxy J7 (2016)
Crash / Error - Crash

Steps to reproduce / Describe in detail - 

App crash when I tap search.
The library is included as module.

Here is the message i get.
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.karv.lxphlaws/com.folioreader.ui.folio.activity.SearchActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.Toolbar.addOnLayoutChangeListener(android.view.View$OnLayoutChangeListener)' on a null object reference
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
                      at android.app.ActivityThread.-wrap14(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6776)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.Toolbar.addOnLayoutChangeListener(android.view.View$OnLayoutChangeListener)' on a null object reference
                      at com.folioreader.ui.folio.activity.SearchActivity.init(SearchActivity.kt:113)
                      at com.folioreader.ui.folio.activity.SearchActivity.onCreate(SearchActivity.kt:106)
                      at android.app.Activity.performCreate(Activity.java:6956)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045) 
                      at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6776) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408) 
```

**Comment by lhj0017** [comment] 2018-09-13 05:16
一样的问题

**Comment by lekhrajtiwari** [comment] 2018-09-21 07:30
hey! did you find any solution for it? am also facing the same issue!!

is there any way to disable search view.

this the error I get.

java.lang.IllegalStateException: menu.findItem(R.id.itemSearch) must not be null
        at com.folioreader.ui.folio.activity.SearchActivity.onCreateOptionsMenu(SearchActivity.kt:226)
        at android.app.Activity.onCreatePanelMenu(Activity.java:3090)
        at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:378)
        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at android.support.v7.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2549)
        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
        at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6946)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by hrishikesh-kadam** [comment] 2018-09-21 07:33
@losscommand @lekhrajtiwari Hey guys are you sure you haven't modified the FolioReader code?
I am unable to reproduce the bug.

**Comment by lekhrajtiwari** [comment] 2018-09-21 07:41
yes @hrishikesh-kadam  implemented the code as given in the guide 

repositories {
    maven {
        url 'http://dl.bintray.com/mobisystech/maven'
    }
}

dependencies {
    implementation 'com.folioreader:folioreader:0.4.3'
}


<manifest ...>
    ...
    <application android:networkSecurityConfig="@xml/network_security_config">
    ...
    </application>
</manifest>

the problem is that when I tried implementing in another test app I was also unable to reproduce the bug!

**Comment by lekhrajtiwari** [comment] 2018-09-25 06:28
@losscommand @hrishikesh-kadam I just found the solution for it, in my case, two libraries with the identical name scheme were creating the conflict. so I suggest importing the library as a module after making some mirror changes in the menu item names

cheers to the filio team.

**Comment by mahavir155** [comment] 2018-09-25 06:30
Glad that you solve the issue yourself. Closing the issue.

**Closed by mahavir155** 2018-09-25 06:30 UTC

**Comment by OluGbengae86** [comment] 2018-11-02 11:58
@lekhrajtiwari Could you please provide a guide on exactly what you did? I'm having the same issue.

**Comment by losscommand** [comment] 2018-11-02 12:07
I had another menu item with the same name. Had to rename it.

**Comment by hrishikesh-kadam** [comment] 2018-11-02 12:31
@OluGbengae86 @losscommand @lekhrajtiwari Please let us know which menu item you had to rename, so that we can rename FolioReader's menu item uniquely to avoid any conflict.

**Comment by OluGbengae86** [comment] 2018-11-02 12:37
@lekhrajtiwari Kindly let's know which menu item, mine not working yet.

**Comment by kvegilla** [comment] 2018-11-02 13:40
@hrishikesh-kadam @OluGbengae86 It was "itemSearch" in main_menu.xml

**Comment by OluGbengae86** [comment] 2018-11-02 13:46
@hrishikesh-kadam @lekhrajtiwari 
So I found the issue. 
The source of the problem is         at com.folioreader.ui.folio.activity.SearchActivity.init(SearchActivity.kt:113)

"SearchActivity.java" was created when I added a search functionality to my app. I simply renamed the activity and the related "activity_search.xml" file and now it's working again. 

Thanks guys

**Comment by losscommand** [comment] 2018-11-02 13:52
Must be a different case. Good to know that there's another solution.
