### ISSUE TITLE
java.lang.NullPointerException:      at org.readium.r2_streamer.server.EpubServer.addLinks (EpubServer.java:68)

### ISSUE THREAD

**Issue by hackstarsj** [FolioReader/FolioReader-Android#215] opened 2018-06-14 19:00 UTC
private void addLinks(EpubPublication publication, String filePath) {
        containsMediaOverlay = false;
        for (Link link : publication.links) {
            if (link.rel.contains("media-overlay")) {
                containsMediaOverlay = true;
                link.href = link.href.replace("port", "localhost:" + getListeningPort() + filePath);
            }
        }

Please Fix this Also

**Comment by OlegTarashkevich** [comment] 2018-06-18 09:51
I had the same issue:

`06-18 05:48:08.241 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha I/System.out: EpubContainer Reading epub at path: /storage/emulated/0/Android/data/de.appcuisine.tigermedia.tigerbooks.alpha/files/1478407.epub
06-18 05:48:08.241 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha I/System.out: EpubContainer Reading file at path: mimetype
06-18 05:48:08.287 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha I/System.out: EpubContainer Reading file at path: META-INF/container.xml
06-18 05:48:08.289 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha I/System.out: EpubContainer Reading file at path: content.opf
06-18 05:48:08.290 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha I/System.out: OPFParser rootFile:= content.opf
06-18 05:48:08.290 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha I/System.out: EpubContainer Reading file at path: toc.ncx
06-18 05:48:08.294 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err: org.xml.sax.SAXParseException: expected: '>' actual: '"' (position:DOCDECL  ncxPUBLIC @1:59 in java.io.StringReader@9e52fce) 
06-18 05:48:08.294 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:146)
06-18 05:48:08.294 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at org.readium.r2_streamer.parser.EpubParser.xmlParser(EpubParser.java:129)
06-18 05:48:08.297 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at org.readium.r2_streamer.parser.NCXParser.parseNCXFile(NCXParser.java:37)
06-18 05:48:08.298 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at org.readium.r2_streamer.parser.OPFParser.parseSpineAndResourcesAndGuide(OPFParser.java:375)
06-18 05:48:08.298 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at org.readium.r2_streamer.parser.OPFParser.parseOpfFile(OPFParser.java:186)
06-18 05:48:08.298 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at org.readium.r2_streamer.parser.EpubParser.parseEpubFile(EpubParser.java:46)
06-18 05:48:08.298 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at org.readium.r2_streamer.server.EpubServer.parse(EpubServer.java:90)
06-18 05:48:08.299 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at org.readium.r2_streamer.server.EpubServer.addEpub(EpubServer.java:40)
06-18 05:48:08.299 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at com.folioreader.ui.folio.activity.FolioActivity.addEpub(FolioActivity.java:175)
06-18 05:48:08.300 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at com.folioreader.ui.folio.activity.FolioActivity.initBook(FolioActivity.java:163)
06-18 05:48:08.301 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at com.folioreader.ui.folio.activity.FolioActivity.setupBook(FolioActivity.java:399)
06-18 05:48:08.301 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at com.folioreader.ui.folio.activity.FolioActivity.onCreate(FolioActivity.java:134)
06-18 05:48:08.301 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at android.app.Activity.performCreate(Activity.java:6664)
06-18 05:48:08.301 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
06-18 05:48:08.301 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
06-18 05:48:08.301 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
06-18 05:48:08.301 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
06-18 05:48:08.302 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
06-18 05:48:08.302 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
06-18 05:48:08.303 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at android.os.Looper.loop(Looper.java:154)
06-18 05:48:08.303 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6077)
06-18 05:48:08.303 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-18 05:48:08.303 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
06-18 05:48:08.303 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
06-18 05:48:08.303 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha I/System.out: EpubParser parserEpubFile() error org.readium.r2_streamer.parser.EpubParserException: Error while parsing
06-18 05:48:08.305 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha D/AndroidRuntime: Shutting down VM
06-18 05:48:08.315 3435-3435/de.appcuisine.tigermedia.tigerbooks.alpha E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                         Process: de.appcuisine.tigermedia.tigerbooks.alpha, PID: 3435
                                                                                         java.lang.Error: FATAL EXCEPTION [main]
                                                                                         Unity version     : 2017.2.0f3
                                                                                         Device model      : Genymotion Google Nexus 9 - 7.0.0 - API 24 - 1536x2048
                                                                                         Device fingerprint: Android/vbox86p/vbox86p:7.0/NRD90M/genymo09131924:userdebug/test-keys
                                                                                         
                                                                                         Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{de.appcuisine.tigermedia.tigerbooks.alpha/com.folioreader.ui.folio.activity.FolioActivity}: java.lang.NullPointerException: Attempt to read from field 'java.util.List org.readium.r2_streamer.model.publication.EpubPublication.links' on a null object reference
                                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                                          Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.List org.readium.r2_streamer.model.publication.EpubPublication.links' on a null object reference
                                                                                             at org.readium.r2_streamer.server.EpubServer.addLinks(EpubServer.java:68)
                                                                                             at org.readium.r2_streamer.server.EpubServer.addEpub(EpubServer.java:42)
                                                                                             at com.folioreader.ui.folio.activity.FolioActivity.addEpub(FolioActivity.java:175)
                                                                                             at com.folioreader.ui.folio.activity.FolioActivity.initBook(FolioActivity.java:163)
                                                                                             at com.folioreader.ui.folio.activity.FolioActivity.setupBook(FolioActivity.java:399)
                                                                                             at com.folioreader.ui.folio.activity.FolioActivity.onCreate(FolioActivity.java:134)
                                                                                             at android.app.Activity.performCreate(Activity.java:6664)
                                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                             at android.os.Looper.loop(Looper.java:154) 
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
06-18 05:48:08.326 646-1398/system_process W/ActivityManager:   Force finishing activity de.appcuisine.tigermedia.tigerbooks.alpha/com.folioreader.ui.folio.activity.FolioActivity
06-18 05:48:08.345 646-1398/system_process W/ActivityManager:   Force finishing activity de.appcuisine.tigermedia.tigerbooks.alpha/de.appcuisine.tigermedia.tigerbooks.ui.splash.SplashActivity
`

**Comment by hackstarsj** [comment] 2018-06-18 10:20
Finally i Stuck Will all Errors i understand Developer works and respect and he make a such a wonderful library for epub .

but finally i create a new library with some customisation.

**Comment by mahavir155** [comment] 2018-06-18 10:29
Really not.. But we'll try to release new version by end of this week or early next week.. we are really excited to release this version, since it will have horizontal scrolling enabled..

**Comment by OlegTarashkevich** [comment] 2018-06-21 11:17
Hi @mahavir155 , Do you have any update? My users see crashes. Please help!

**Comment by hrishikesh-kadam** [comment] 2018-06-22 07:21
@OlegTarashkevich Upgrade to v0.3.10

**Comment by mahavir155** [comment] 2018-06-22 07:31
@OlegTarashkevich Crash should be fixed in v0.3.10.. FYI Horizontal scrolling is not released yet.. We'll need one more week to have Horizontal scrolling.. Meanwhile you can use 0.3.10..

**Comment by OlegTarashkevich** [comment] 2018-06-22 07:32
Thank you @hrishikesh-kadam @mahavir155 
v0.3.10 has the same crash.
The "publication" object is null. It's the reason of the crash.
Looks like the bug while parsing: `org.xml.sax.SAXParseException: expected: '>' actual: '"`
Please look at the my previous post where I've provided the logs.

![screen shot 2018-06-22 at 10 20 52](https://user-images.githubusercontent.com/13828110/41763173-14d43ea4-7606-11e8-8bc7-3d2b99281f2d.png)

**Comment by mahavir155** [comment] 2018-06-22 07:43
any possibility to share epub?

**Comment by hrishikesh-kadam** [comment] 2018-06-22 08:12
@OlegTarashkevich I have opened new issue on behalf of you - #221
This issue is different from yours so let us have conversation on #221 

@mahavir155 we can close this issue.

**Closed** 2018-06-22 08:15 UTC
